name: Test httpbin API

on:
  push:
    branches:
      - main  # Se ejecutará en cada push a la rama main
  pull_request:
    branches:
      - main  # También se ejecutará en los pull requests hacia la rama main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Revisa el código de tu repositorio

    - name: Make a request to httpbin
      run: |
        curl -X GET https://httpbin.org/get  # Realiza una solicitud GET a httpbin.org

